### ISSUE TITLE
[M0-Dev] La lógica de negocio requiere de canciones

### ISSUE THREAD

**Issue by luistf24** [Carlos-SE/App-chores#15]
Según lo visto #2 y #5 ya que es la unidad básica con la que se va a trabajar para implementar la lógica de negocio. Esta entidad tiene que contener todo lo necesario para identificar una canción sin confusión

**Comment by JJ** [comment]
Creo que según este planteamiento del problema sólo podrías poner el título y quizás el año. Tampoco queda claro qué es "una canción". "No women no cry" ¿es siempre la misma canción? ¿O es diferente la de Bob Marley y la de Boney M?

**Comment by JJ** [comment]
En resumen, el problema fundamental aquí es "cómo identificar una canción sin confusión". No tiene soluciones únicas, claro, pero es un problema que te tienes que plantear y poner la solución en el código (que sea compatible con la lógica de megocio)
