### ISSUE TITLE
Implementación del algoritmo de recomendación

### ISSUE THREAD

**Issue by Carlos-SE** [Carlos-SE/App-chores#29]
Dada una lista de conjuntos de canciones, géneros y colaboraciones se tienen que obtener datos cuantificables sobre dicha lista, que permitan clasificar los gustos del propietario de esta.

Este algoritmo de recomendación, surge de las historias de usuario [HU03](https://github.com/Carlos-SE/App-chores/issues/5) y [HU02](https://github.com/Carlos-SE/App-chores/issues/3), donde destacamos los gustos y las colaboraciones entre artistas.

## Pasos a tener en cuenta
1. Para descubrir música nueva lo más importante es que sea de géneros que al usuario le gusten, por eso esto tomará la mayor ponderación.
2. Tras esto, que haya presencia de colaboraciones entre unos artistas que le gusten al usuario con unos nuevos ponderará positivamente para que se sugieran canciones de estos últimos.

## Implementación
Obtener los datos de un objeto de tipo `Playlist` y operar con ellos

**Comment by Carlos-SE** [comment]
Se considera que una recomendación es buena en el momento en el que haya una colaboración entre artirtas.

Luego, según el tipo de género de la canción y la cantidad de canciones que tenga en la lista de dicho género suma más puntuación a una variable que representa lo "buena" sugerencia que es una canción

**Comment by Carlos-SE** [comment]
Separar del test ya que esta función no es solo parte de él.

**Comment by JJ** [comment]
No estás enlazando ninguna historia de usuario, por lo que es erróneo.

**Comment by Carlos-SE** [comment]
Como se necesita poder solucionar los problemas planteados en las historias de usuario, presentes en la descripción del problema. Se deberá asignar distintos pesos a los atributos de las canciones para obtener si es una buena o mala recomendación.

Con la HU03, vemos la necesidad de descubrir canciones de artistas que hayan colaborado con los que suele escuchar, con esto, ya sería una buena recomendación.

Con la HU02, notamos que depende de los gustos. Por ello se valorará el género de la canción en relación con el porcentaje de música de ese género en la playlist. Para que sea válido, tendremos que más de un 25% (se toma este valor porque se considera adecuado) de su lista sea de ese género.
